version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
