version: '3'
services:
  app:
    build: ./backend
    ports:
      - '8080:8080'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      FRONTEND_HOST: http://localhost:3000
      BACKEND_HOST: http://localhost:8080
      EMAIL_USERNAME: ER_radd@mail.ru

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
