server:
  error:
    include-message: always
    include-binding-errors: always

hosts:
  backend: ${BACKEND_HOST}
  frontend: ${FRONTEND_HOST}

spring:
  thymeleaf:
    enabled: true
    suffix: .html
    prefix: classpath:/templates/

  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    host: smtp.mail.ru
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

security:
  cors:
    allowed-origins:
      - ${hosts.frontend}
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
    allowed-headers: ["*"]
